### ISSUE TITLE
Unmaintained - Ownership?

### ISSUE THREAD

**Issue by sseide** [EvilDevRu/node-redis-dump#3]
Hello @EvilDevRu,

as your package seems to be unmaintained i like to ask if you would be willing to transfer this package together with the npm package to me to be able to incorporate all the fixes needed by now for using it with redis commander. 
And now some security problems came up with one of the dependencies, therefore they needs to be updated as well.

At least looking at the npmjs.org side your package is only used from Redis Commander.
Would rthis transfer be possible?

If not I need to fork it and publish a new package but maintaining this further might be easier...

Looking for an answer,
S. Seide

**Comment by EvilDevRu** [comment]
Hi. Sorry for very long answer. I will update project soon

**Comment by sseide** [comment]
Hello,
thanks for answering. 
There is a long patch file by now with fixes needed for Redis Commander to work ([redis-dump.diff](https://github.com/joeferner/redis-commander/blob/master/docker/redis-dump.diff)) we apply on every Redis Commander docker image build.

I'll create an PR with it too as well as the security update needed for underscore to latest version

Thanks,
S. Seide

**Comment by EvilDevRu** [comment]
Fixed. Please check.
